name: Container registry

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./project

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/isen-python:latest
            ${{ secrets.DOCKER_USERNAME }}/isen-python:dev-${{ env.SHORT_SHA }}

      - name: Scan image with Trivy (HIGH and CRITICAL only)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/isen-python:dev-${{ env.SHORT_SHA }}
          severity: 'HIGH,CRITICAL'
          format: 'table'
          exit-code: '0'

      - name: Generate SBOM from project files with Syft
        uses: anchore/sbom-action@v0.15.1
        with:
          path: ./project
          output-file: sbom.syft.json
          format: syft-json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-syft-json
          path: sbom.syft.json
