name: Build and Push Docker image to Artifact Registry

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./project

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/isen-python:latest
            ${{ secrets.DOCKER_USERNAME }}/isen-python:dev-${{ env.SHORT_SHA }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@2
        with:
          project_id: ancient-wave-458212-n3
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true 

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
          
      - name: Build and push to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: ./project
          push: true
          tags: |
            europe-west1-docker.pkg.dev/ancient-wave-458212-n3/docker-repo/isen-python:latest
            europe-west1-docker.pkg.dev/ancient-wave-458212-n3/docker-repo/isen-python:dev-${{ env.SHORT_SHA }}