name: Build and Push Docker image to Artifact Registry

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./project

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./project
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/isen-python:latest
            ${{ secrets.DOCKER_USERNAME }}/isen-python:dev-${{ env.SHORT_SHA }}
            europe-west1-docker.pkg.dev/ancient-wave-458212-n3/docker-repo/isen-python:latest
            europe-west1-docker.pkg.dev/ancient-wave-458212-n3/docker-repo/isen-python:dev-${{ env.SHORT_SHA }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'hello-cloud-run'
          image: 'europe-west1-docker.pkg.dev/ancient-wave-458212-n3/docker-repo/isen-python:latest'
          region: 'europe-west1'

      - name: Use output
        run: curl "${{ steps.deploy.outputs.url }}"
