name: ZAP Baseline DAST Scan

on:
  push:
    branches:
      - main 

jobs:
  zap_scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Requirement
        run: |
          pip install -r requirements.txt

      - name: Start the app with Docker
        run: |
            docker-compose up -d
            sleep 15

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:8080' 
          cmd_options: '-t 60 -I -J zap-report.json -x zap-report.xml'